In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [10]:
path=pd.read_excel("C:/Users/andre/OneDrive/Escritorio/LenguajesProgramacion/DataAnalyticsPython/Data/OfertaEducativa.xls")
path.head()

,DIRECCIÓN DE FORMACIÓN TÉCNICA SUPERIOR (DFTS),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,CARRERA,ESTABLECIMIENTO,DIRECCIÓN,BARRIO,HORARIO,TELÉFONO,CORREO,PERFIL DEL EGRESADO,REQUISITOS,DURACIÓN
1,ADMINISTRACIÓN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TS en Administración de Seguros,IFTS Nº 01,San Martín 665 4º Piso,San Nicolas,7:45 a 11 18 a 22,4318-7700,dfts_ifts1_de1@bue.edu.ar,Estarás capacitado para: · Asesorar a las empr...,Secundario completo,3 años
3,TS en Administración de Empresas,IFTS Nº 03,Angel J. Carranza 2045,Palermo,18:30 a 22:15,4772-1659/8586,DFTS_IFTS3_DE9@bue.edu.ar,Estarás capacitado en las actividades propias ...,Secundario completo,3 años
4,NaN,IFTS Nº 07,Gaona 1502,Caballito,18:30 a 21:45,4581-8804,DFTS_IFTS7_DE7@bue.edu.ar,NaN,NaN,NaN